### ISSUE TITLE
Endless loop if no ACL file was yet present for some file

### ISSUE THREAD

**Issue by FlorSanders** [0wntech/ownacl#1]
When calling either the `readAccessControl()` or the `read()` functions on a file for which no ACL file is yet present, the program seems to get stuck in an endless loop of getting the parent folder's ACL file.

Code snippet:
```js
var aclurl = `${filename}.acl`;
const acl = new aclClient(aclurl);
acl.readAccessControl().then(permissions => {
    // Do something with permissions
}).catch(err => console.log(err));
```

For files that already have their own ACL file this works perfectly, though if no ACL file is present yet I can see this in the browser's console:

```http
OPTIONS https://flordigipolis.solid.community/private/iot/new.ttl.acl
[HTTP/1.1 204 No Content 17ms]

GET https://flordigipolis.solid.community/private/iot/new.ttl.acl
[HTTP/1.1 404 Not Found 212ms]

GET https://flordigipolis.solid.community/private/.acl
[HTTP/1.1 200 OK 200ms]

GET https://flordigipolis.solid.community/private/.acl
[HTTP/1.1 200 OK 200ms]
```

Once it starts calling `GET https://flordigipolis.solid.community/private/.acl` it goes on indefinitely.
I suppose the desired behaviour would be to end up [here](https://github.com/0wntech/ownacl/blob/master/lib/read.js#L44) and to create a new ACL file when/if the error gets caught.
But since the program persists in an endless loop this isn't an option.

**Comment by ludwigschubi** [comment]
Hey thanks for opening the issue and checking out ownacl!

I'm so sorry for the long delay on a reply ... I didnt see this issue until now, but I think I encountered a similar error and fixed it afterwards, so maybe it works now. If you still need this functionality, could you verify that the bug still exists with the latest version? If it does i would investigate further 👍

**Comment by ludwigschubi** [comment]
Also if you are accessing a private folder make sure to authenticate the ownacl client by modifying it's fetchers ._fetch method:
```
const client = new SolidNodeClient();
await client.login(config);
aclClient.fetcher._fetch = client.fetch.bind(client);
```
